### PR TITLE
Move variables to external script and new variable 'domain'

### PR DESCRIPTION
**Pull request by LubuWest**
I moved the variables to external script and put them into the header (the additional variable 'domain' is needed, as not all GNU Social users are on https://quitter.se). This way the variables are easier to customize for users of the script. Most importantly the script can be used in templates for popular static website creators like pelican (https://github.com/getpelican/pelican) with all variables in configuration files.

### CODE REVIEW

**Comment by blankoworld** [comment]
Hi,

Thanks for the pull request. For now I have no time to see changes.
I will have a look this week-end or next week.

**Comment by LubuWest** [comment]
I extended eli.js to automatically show pictures from attachments in GNU Social in the timeline. Please have a look. I think this would really improve the usefullness of the script.

**Comment by blankoworld** [comment]
Finally it makes more time than expected to be available to check your work.

Let's have a look to each commit.

For https://github.com/LubuWest/eli/commit/db327f3407bdaa97a0ac6e4a8e1093008bee6db3, I think it's useless to add a new variable "domain" as you can change the API one which is present for this.
As you can see here: http://eli.depotoi.re/ we change the API URL so that we use another server. As I do in Makefly here: https://github.com/blankoworld/makefly/blob/perso/makefly.rc#L24
I likes having default parameters. That's why I use qvitter as default API URL in eli.js and eli.max.js.

For readable purpose, is that possible you adapt also eli.max.js so that it reflects eli.js changes? In fact eli.js file is just a remake of eli.max.js by using a reducer/compression algorithm. The main file is so eli.max.js.

I don't understand how you make an external configuration file. Have you any example about this? It's very interesting as I always attempt to include ELI in Makefly project (Cf. https://github.com/blankoworld/makefly) which is a static weblog engine too.

For https://github.com/LubuWest/eli/commit/db327f3407bdaa97a0ac6e4a8e1093008bee6db3 I think it would be better if you adapt eli.max.js as explained before.

We can discuss about this with Jabber if needed. Give me a date, I'm available here (xmpp only): olivier [AT] olivier [DOT] dossmann [DOT] net

**Comment by LubuWest** [comment]
Hi Olivier,
I use the script in my Pelican Theme simplegrey-free:
https://github.com/getpelican/pelican-themes/pull/291
The configuration is in some Python file. Pelican puts the variables to
a placeholder in the html base templates (It doesn't change Javascript
files).  The placeholders are Javascript directly in the Html-File.
I think its easier for the user to put a domain in the configuration
file than domain + "/api"
I try to adjust the eli.max.js and make a pull request.
Yours, LubuWest

**Comment by blankoworld** [comment]
Ok, I now understand how it could work here: https://github.com/LubuWest/pelican-themes/blob/e37703981860afc3b87ca2cbfa68de6b7231ec91/simplegrey-free/templates/base.html

Seems to be very fun to include it into Pelican :-P

I don't understand the problem of image yet. But today I will check all of this @home and merde your pull request.

I also have 2 questions (not linked to your merge):

  * how did you find ELI? From a website, a search engine, etc.?
  * have you seen that some GNU Social have HTTPS with a self-signed certificate? Have you any idea how to make a "no-check-certificate" for these websites in javascript?

**Comment by blankoworld** [comment]
I merge your pull request.

I adapt some things as pictures so that they don't be displayed very well (with CSS) by using timeline from nidron (user) on quit.im.

I delete the changes about CSS file as you minimize the height of the badge in default ELI CSS. If you want to adapt the CSS to your own, you need to add supplementary CSS in your Pelican's theme.

For an example just add:
```css
#eli_widget {
height: 150px;
overflow-x: visible;
overflow-y: auto;
}
```

Don't hesitate to contact me for any problem.

I thank you a lot for your contribution ;)

**Comment by LubuWest** [comment]
Hi,
thanks for the merges. I will adapt the changes to my pelican theme.
Btw, the width of the pictures is hard-coded to 200px ("width=200") in
eli.js. In the css it is 240px. I think one of them can be deleted,
probably the one in eli.js.
I found the script while searching for javascript and gnu social on
github. I thought there must be something like the twitter widget for
the free software world. Some other projects refered to identi.ca and
were too old/did not work.
For the self-signed certificate problem there is imo no javascript
solution. It would be too insecure for a browser to allow switching off
certificate checking via javascript... I hate the certificate mafia,
too. But i think there is no solution to the problem. I'm waiting for
the Mozilla certificate authority...

**Comment by blankoworld** [comment]
Oh I see (for pictures width). Thanks. I make another commit to fix it.

But what's strange is that on my side when GNU Social offers a pictures (in attachement), I see it twice on ELI. Have you the same problem?
Because of the fact we had the attachement after the item_content (with image_link). But the pictures is already in the item_content (on my side).
Any explanation?

PS: If you have any other functionnalities, don't hesitate to suggest them via the pull request button ;)

**Pull request merged**
